# Generated by Django 3.1.6 on 2021-02-20 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=100, verbose_name='slug')),
                ('name', models.CharField(max_length=100, verbose_name='Başlık')),
                ('description', models.CharField(max_length=1000, verbose_name='Yazı')),
                ('image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Başlık Resmi')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to=settings.AUTH_USER_MODEL, verbose_name='Yazar ')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
